# How to use pyMetadataEditor

In [1]:
from pymetadataeditor import MetadataEditor
import os

## Examples of the interface

In [2]:
your_api_key = os.getenv("API_KEY")
api_url = os.getenv("API_URL")
me = MetadataEditor(api_url=api_url, api_key=your_api_key, verify_ssl=False)

### Listing your projects

In [3]:
me.list_projects(limit=8)

/Users/gblackadder/Library/Caches/pypoetry/virtualenvs/pymetadataeditor-HQrUvkIt-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.ihsn.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,published,created,changed,varcount,created_by,changed_by,is_shared,thumbnail,template_uid,username,username_cr,collections
id,,,,,,,,,,,,,,,,,,,,
3035,timeseries,IMF_APDREO_GGXCNL_GDP,IMF_APDREO_GGXCNL_GDP,"General government net lending/borrowing, perc...",None,,0,0,None,2024-11-20T15:28:40+00:00,2024-11-20T15:28:40+00:00,None,2,2,None,thumbnail-3035.jpg,timeseries-system-en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3034,timeseries,IMF_APDREO_NGDP_R_PPP_PC_PCH,IMF_APDREO_NGDP_R_PPP_PC_PCH,"Gross domestic product, constant prices, purch...",None,,0,0,None,2024-11-20T15:28:37+00:00,2024-11-20T15:28:37+00:00,None,2,2,None,thumbnail-3034.jpg,8603d94e27bccc2bdad1e00dbbf0fe32en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3033,timeseries,IMF_APDREO_BCA_GDP_BP6,IMF_APDREO_BCA_GDP_BP6,"Balance of Payments, Current Account, Total, N...",None,,0,0,None,2024-11-20T15:28:35+00:00,2024-11-20T15:28:35+00:00,None,2,2,None,thumbnail-3033.jpg,8603d94e27bccc2bdad1e00dbbf0fe32en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3032,timeseries,IMF_APDREO_PCPIE_PCH,IMF_APDREO_PCPIE_PCH,"Consumer Prices, end of period, percent change...",None,,0,0,None,2024-11-20T15:28:33+00:00,2024-11-20T15:28:33+00:00,None,2,2,None,thumbnail-3032.jpg,8603d94e27bccc2bdad1e00dbbf0fe32en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3024,timeseries,IMF_APDREO_LUR,IMF_APDREO_LUR,Unemployment rate (Asia and Pacific Regional E...,None,,0,0,None,2024-11-19T18:50:45+00:00,2024-11-20T15:28:32+00:00,None,2,2,None,thumbnail-3024.jpg,8603d94e27bccc2bdad1e00dbbf0fe32en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3031,timeseries,IMF_APDREO_NGDP_RPCH,IMF_APDREO_NGDP_RPCH,"Gross domestic product, constant prices, Natio...",None,,0,0,None,2024-11-20T15:28:30+00:00,2024-11-20T15:28:30+00:00,None,2,2,None,thumbnail-3031.jpg,8603d94e27bccc2bdad1e00dbbf0fe32en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3030,timeseries,IMF_APDREO_PCPI_PCH,IMF_APDREO_PCPI_PCH,"Consumer Prices, period average, percent chang...",None,,0,0,None,2024-11-20T15:28:27+00:00,2024-11-20T15:28:27+00:00,None,2,2,None,thumbnail-3030.jpg,8603d94e27bccc2bdad1e00dbbf0fe32en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3029,timeseries-db,IMF_APDREO,IMF_APDREO,"IMF, Asia-Pacific Regional Economic Outlook (A...",None,,0,0,None,2024-11-20T15:28:26+00:00,2024-11-20T15:28:26+00:00,None,2,2,None,thumbnail-3029.jpg,f3e2d1c8c494be27bc229463a265a33d,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."

In [4]:
me.count_projects()

1473

### Creating a new indicator project

In [5]:
demo_name = "GB20241030_demo"

In [6]:
series_description = {
                        "idno": demo_name,
                        "doi": "V1",
                        "name": "Version 1",
                        "display_name": "Version 1"
                     }

indicator_id = me.create_project_log({"idno": demo_name, "series_description": series_description}, "indicator")

In [7]:
me.list_projects(limit=3, sort_by="updated_desc")

,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,published,created,changed,varcount,created_by,changed_by,is_shared,thumbnail,template_uid,username,username_cr,collections
id,,,,,,,,,,,,,,,,,,,,
3373,timeseries,e85bec4a-34fc-4a1b-af88-e93cb2750d36,GB20241030_demo,Version 1,None,,0,0,None,2024-11-26T21:38:18+00:00,2024-11-26T21:38:18+00:00,None,24,24,None,None,8603d94e27bccc2bdad1e00dbbf0fe32en,Gordon Blackadder,Gordon Blackadder,[]
3035,timeseries,IMF_APDREO_GGXCNL_GDP,IMF_APDREO_GGXCNL_GDP,"General government net lending/borrowing, perc...",None,,0,0,None,2024-11-20T15:28:40+00:00,2024-11-20T15:28:40+00:00,None,2,2,None,thumbnail-3035.jpg,timeseries-system-en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."
3034,timeseries,IMF_APDREO_NGDP_R_PPP_PC_PCH,IMF_APDREO_NGDP_R_PPP_PC_PCH,"Gross domestic product, constant prices, purch...",None,,0,0,None,2024-11-20T15:28:37+00:00,2024-11-20T15:28:37+00:00,None,2,2,None,thumbnail-3034.jpg,8603d94e27bccc2bdad1e00dbbf0fe32en,Olivier Dupriez,Olivier Dupriez,"[{'id': '119', 'title': 'IMF_APDREO', 'sid': '..."

In [8]:
me.get_project_by_id(indicator_id)

id                                                               3373
idno                             e85bec4a-34fc-4a1b-af88-e93cb2750d36
type                                                       timeseries
title                                                       Version 1
abbreviation                                                     None
authoring_entity                                                 None
nation
year_start                                                          0
year_end                                                            0
metafile                                                         None
dirpath                              0084ae4bc24c0795d1e6a4f58444d39b
varcount                                                         None
published                                                        None
created                                     2024-11-26T21:38:18+00:00
changed                                     2024-11-26T21:38:18+00:00
created_by                                                         24
changed_by                                                         24
thumbnail                                                        None
metadata            {'series_description': {'idno': 'GB20241030_de...
template_uid                       8603d94e27bccc2bdad1e00dbbf0fe32en
is_shared                                                        None
study_idno                                            GB20241030_demo
dtype: object

In [9]:
me.get_project_metadata_by_id(indicator_id, output_mode='dict')

{'series_description': {'idno': 'GB20241030_demo', 'name': 'Version 1'}}

So we've gotten back less than expected. That's because the default template for indicators doesn't include the top level idno or a series_description.display_name. Better to start then with an outline of the actual data we want.

# Starting with outlines

The metadata can be both large and hierarchical. Starting with a skeleton outline makes things easier.

Outlines are available in three modes - dictionary, pydantic model and as an Excel file.

## Dictionaries
Dictionaries are created like so:

In [10]:
indicator_dict = me.make_metadata_outline('indicator', output_mode='dict')
indicator_dict

{'metadata_information': {'title': None,
  'idno': None,
  'producers': [{'name': None,
    'abbr': None,
    'affiliation': None,
    'role': None}],
  'prod_date': None,
  'version': None},
 'series_description': {'idno': '',
  'alternate_identifiers': [{'name': None,
    'identifier': '',
    'database': None,
    'uri': None,
    'notes': None}],
  'name': '',
  'aliases': [{'alias': None}],
  'database_id': None,
  'definition_short': None,
  'definition_long': None,
  'definition_references': [{'source': None, 'uri': None, 'note': None}],
  'relevance': None,
  'methodology': None,
  'derivation': None,
  'imputation': None,
  'statistical_concept': None,
  'concepts': [{'name': '', 'definition': None, 'uri': None}],
  'aggregation_method': None,
  'sources': [{'id': None,
    'name': '',
    'organization': None,
    'type': None,
    'note': None}],
  'sources_note': None,
  'data_collection': {'data_source': None,
   'method': None,
   'period': None,
   'note': None,
   'uri': None},
  'compliance': [{'standard': '',
    'abbreviation': None,
    'custodian': None,
    'uri': None}],
  'framework': [{'name': '',
    'abbreviation': None,
    'custodian': None,
    'description': None,
    'goal_id': None,
    'goal_name': None,
    'goal_description': None,
    'target_id': None,
    'target_name': None,
    'target_description': None,
    'indicator_id': None,
    'indicator_name': None,
    'indicator_description': None,
    'uri': None,
    'notes': None}],
  'limitation': None,
  'quality_checks': None,
  'quality_note': None,
  'validation_rules': [],
  'sources_discrepancies': None,
  'adjustments': [],
  'missing': None,
  'errata': [{'type': None, 'description': None}],
  'time_periods': [{'start': None, 'end': None}],
  'ref_country': [{'name': None, 'code': None}],
  'geographic_units': [{'name': '', 'code': None, 'type': None}],
  'bbox': [{'west': None, 'east': None, 'south': None, 'north': None}],
  'authoring_entity': [{'name': '',
    'affiliation': None,
    'abbreviation': '',
    'email': '',
    'uri': None}],
  'mandate': {'mandate': None, 'uri': None},
  'measurement_unit': None,
  'dimensions': [{'name': None, 'label': '', 'description': None}],
  'release_calendar': None,
  'periodicity': None,
  'base_period': None,
  'series_break': None,
  'keywords': [{'name': '', 'vocabulary': None, 'uri': None}],
  'topics': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'themes': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'disciplines': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'disaggregation': None,
  'languages': [{'name': None, 'code': None}],
  'acronyms': [{'acronym': '', 'expansion': '', 'occurence': None}],
  'related_indicators': [{'code': None,
    'uri': None,
    'label': None,
    'relationship': None,
    'type': None}],
  'series_groups': [{'name': None,
    'description': None,
    'version': None,
    'uri': None}],
  'notes': [{'note': None, 'type': None}],
  'license': [{'name': None, 'uri': None, 'note': None}],
  'confidentiality': None,
  'confidentiality_status': None,
  'confidentiality_note': None,
  'links': [{'type': None, 'description': None, 'uri': None}],
  'api_documentation': [{'description': None, 'uri': None}],
  'contacts': [{'name': None,
    'role': None,
    'affiliation': None,
    'email': None,
    'telephone': None,
    'uri': None}]},
 'tags': [{'tag': None, 'tag_group': None}]}

and updated in the usual way:

In [11]:
indicator_dict['metadata_information']['producers'][0]['name'] = "example_producer"
indicator_dict

{'metadata_information': {'title': None,
  'idno': None,
  'producers': [{'name': 'example_producer',
    'abbr': None,
    'affiliation': None,
    'role': None}],
  'prod_date': None,
  'version': None},
 'series_description': {'idno': '',
  'alternate_identifiers': [{'name': None,
    'identifier': '',
    'database': None,
    'uri': None,
    'notes': None}],
  'name': '',
  'aliases': [{'alias': None}],
  'database_id': None,
  'definition_short': None,
  'definition_long': None,
  'definition_references': [{'source': None, 'uri': None, 'note': None}],
  'relevance': None,
  'methodology': None,
  'derivation': None,
  'imputation': None,
  'statistical_concept': None,
  'concepts': [{'name': '', 'definition': None, 'uri': None}],
  'aggregation_method': None,
  'sources': [{'id': None,
    'name': '',
    'organization': None,
    'type': None,
    'note': None}],
  'sources_note': None,
  'data_collection': {'data_source': None,
   'method': None,
   'period': None,
   'note': None,
   'uri': None},
  'compliance': [{'standard': '',
    'abbreviation': None,
    'custodian': None,
    'uri': None}],
  'framework': [{'name': '',
    'abbreviation': None,
    'custodian': None,
    'description': None,
    'goal_id': None,
    'goal_name': None,
    'goal_description': None,
    'target_id': None,
    'target_name': None,
    'target_description': None,
    'indicator_id': None,
    'indicator_name': None,
    'indicator_description': None,
    'uri': None,
    'notes': None}],
  'limitation': None,
  'quality_checks': None,
  'quality_note': None,
  'validation_rules': [],
  'sources_discrepancies': None,
  'adjustments': [],
  'missing': None,
  'errata': [{'type': None, 'description': None}],
  'time_periods': [{'start': None, 'end': None}],
  'ref_country': [{'name': None, 'code': None}],
  'geographic_units': [{'name': '', 'code': None, 'type': None}],
  'bbox': [{'west': None, 'east': None, 'south': None, 'north': None}],
  'authoring_entity': [{'name': '',
    'affiliation': None,
    'abbreviation': '',
    'email': '',
    'uri': None}],
  'mandate': {'mandate': None, 'uri': None},
  'measurement_unit': None,
  'dimensions': [{'name': None, 'label': '', 'description': None}],
  'release_calendar': None,
  'periodicity': None,
  'base_period': None,
  'series_break': None,
  'keywords': [{'name': '', 'vocabulary': None, 'uri': None}],
  'topics': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'themes': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'disciplines': [{'id': None,
    'name': '',
    'parent_id': None,
    'vocabulary': None,
    'uri': None}],
  'disaggregation': None,
  'languages': [{'name': None, 'code': None}],
  'acronyms': [{'acronym': '', 'expansion': '', 'occurence': None}],
  'related_indicators': [{'code': None,
    'uri': None,
    'label': None,
    'relationship': None,
    'type': None}],
  'series_groups': [{'name': None,
    'description': None,
    'version': None,
    'uri': None}],
  'notes': [{'note': None, 'type': None}],
  'license': [{'name': None, 'uri': None, 'note': None}],
  'confidentiality': None,
  'confidentiality_status': None,
  'confidentiality_note': None,
  'links': [{'type': None, 'description': None, 'uri': None}],
  'api_documentation': [{'description': None, 'uri': None}],
  'contacts': [{'name': None,
    'role': None,
    'affiliation': None,
    'email': None,
    'telephone': None,
    'uri': None}]},
 'tags': [{'tag': None, 'tag_group': None}]}

## Pydantic

Pydantic is a nice python library for defining and validating data schemas. An outline for the indicator schema can be created like so:

In [12]:
indicator_pydantic = me.make_metadata_outline('indicator', 'pydantic')
indicator_pydantic

IHSN_INDICATOR_1-0_Template_v01_EN(metadata_information=metadata_information(title=None, idno=None, producers=[Producer(name=None, abbr=None, affiliation=None, role=None)], prod_date=None, version=None), series_description=series_description(idno='', alternate_identifiers=[Alternate_identifier(name=None, identifier='', database=None, uri=None, notes=None)], name='', aliases=[Aliase(alias=None)], database_id=None, definition_short=None, definition_long=None, definition_references=[Definition_reference(source=None, uri=None, note=None)], relevance=None, methodology=None, derivation=None, imputation=None, statistical_concept=None, concepts=[Concept(name='', definition=None, uri=None)], aggregation_method=None, sources=[Source(id=None, name='', organization=None, type=None, note=None)], sources_note=None, data_collection=data_collection(data_source=None, method=None, period=None, note=None, uri=None), compliance=[ComplianceItem(standard='', abbreviation=None, custodian=None, uri=None)], framework=[FrameworkItem(name='', abbreviation=None, custodian=None, description=None, goal_id=None, goal_name=None, goal_description=None, target_id=None, target_name=None, target_description=None, indicator_id=None, indicator_name=None, indicator_description=None, uri=None, notes=None)], limitation=None, quality_checks=None, quality_note=None, validation_rules=[], sources_discrepancies=None, adjustments=[], missing=None, errata=[ErrataItem(type=None, description=None)], time_periods=[Time_period(start=None, end=None)], ref_country=[Ref_countryItem(name=None, code=None)], geographic_units=[Geographic_unit(name='', code=None, type=None)], bbox=[BboxItem(west=None, east=None, south=None, north=None)], authoring_entity=[Authoring_entityItem(name='', affiliation=None, abbreviation='', email='', uri=None)], mandate=mandate(mandate=None, uri=None), measurement_unit=None, dimensions=[Dimension(name=None, label='', description=None)], release_calendar=None, periodicity=None, base_period=None, series_break=None, keywords=[Keyword(name='', vocabulary=None, uri=None)], topics=[Topic(id=None, name='', parent_id=None, vocabulary=None, uri=None)], themes=[Theme(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disciplines=[Discipline(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disaggregation=None, languages=[Language(name=None, code=None)], acronyms=[Acronym(acronym='', expansion='', occurence=None)], related_indicators=[Related_indicator(code=None, uri=None, label=None, relationship=None, type=None)], series_groups=[Series_group(name=None, description=None, version=None, uri=None)], notes=[Note(note=None, type=None)], license=[LicenseItem(name=None, uri=None, note=None)], confidentiality=None, confidentiality_status=None, confidentiality_note=None, links=[Link(type=None, description=None, uri=None)], api_documentation=[Api_documentationItem(description=None, uri=None)], contacts=[Contact(name=None, role=None, affiliation=None, email=None, telephone=None, uri=None)]), tags=[Tag(tag=None, tag_group=None)])

It can be updated using dot notation, for example:

In [13]:
indicator_pydantic.metadata_information.producers[0].name = "example_producer"
indicator_pydantic

IHSN_INDICATOR_1-0_Template_v01_EN(metadata_information=metadata_information(title=None, idno=None, producers=[Producer(name='example_producer', abbr=None, affiliation=None, role=None)], prod_date=None, version=None), series_description=series_description(idno='', alternate_identifiers=[Alternate_identifier(name=None, identifier='', database=None, uri=None, notes=None)], name='', aliases=[Aliase(alias=None)], database_id=None, definition_short=None, definition_long=None, definition_references=[Definition_reference(source=None, uri=None, note=None)], relevance=None, methodology=None, derivation=None, imputation=None, statistical_concept=None, concepts=[Concept(name='', definition=None, uri=None)], aggregation_method=None, sources=[Source(id=None, name='', organization=None, type=None, note=None)], sources_note=None, data_collection=data_collection(data_source=None, method=None, period=None, note=None, uri=None), compliance=[ComplianceItem(standard='', abbreviation=None, custodian=None, uri=None)], framework=[FrameworkItem(name='', abbreviation=None, custodian=None, description=None, goal_id=None, goal_name=None, goal_description=None, target_id=None, target_name=None, target_description=None, indicator_id=None, indicator_name=None, indicator_description=None, uri=None, notes=None)], limitation=None, quality_checks=None, quality_note=None, validation_rules=[], sources_discrepancies=None, adjustments=[], missing=None, errata=[ErrataItem(type=None, description=None)], time_periods=[Time_period(start=None, end=None)], ref_country=[Ref_countryItem(name=None, code=None)], geographic_units=[Geographic_unit(name='', code=None, type=None)], bbox=[BboxItem(west=None, east=None, south=None, north=None)], authoring_entity=[Authoring_entityItem(name='', affiliation=None, abbreviation='', email='', uri=None)], mandate=mandate(mandate=None, uri=None), measurement_unit=None, dimensions=[Dimension(name=None, label='', description=None)], release_calendar=None, periodicity=None, base_period=None, series_break=None, keywords=[Keyword(name='', vocabulary=None, uri=None)], topics=[Topic(id=None, name='', parent_id=None, vocabulary=None, uri=None)], themes=[Theme(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disciplines=[Discipline(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disaggregation=None, languages=[Language(name=None, code=None)], acronyms=[Acronym(acronym='', expansion='', occurence=None)], related_indicators=[Related_indicator(code=None, uri=None, label=None, relationship=None, type=None)], series_groups=[Series_group(name=None, description=None, version=None, uri=None)], notes=[Note(note=None, type=None)], license=[LicenseItem(name=None, uri=None, note=None)], confidentiality=None, confidentiality_status=None, confidentiality_note=None, links=[Link(type=None, description=None, uri=None)], api_documentation=[Api_documentationItem(description=None, uri=None)], contacts=[Contact(name=None, role=None, affiliation=None, email=None, telephone=None, uri=None)]), tags=[Tag(tag=None, tag_group=None)])

## Printing

The pydantic metadata object also contains a helper function for printing metadata:

In [14]:
indicator_pydantic.pretty_print()

IHSN_INDICATOR_1-0_Template_v01_EN(
    metadata_information=metadata_information(
        title=None,
        idno=None,
        producers=[Producer(name='example_producer', abbr=None, affiliation=None, role=None)],
        prod_date=None,
        version=None
    ),
    series_description=series_description(
        idno='',
        alternate_identifiers=[
            Alternate_identifier(name=None, identifier='', database=None, uri=None, notes=None)
        ],
        name='',
        aliases=[Aliase(alias=None)],
        database_id=None,
        definition_short=None,
        definition_long=None,
        definition_references=[Definition_reference(source=None, uri=None, note=None)],
        relevance=None,
        methodology=None,
        derivation=None,
        imputation=None,
        statistical_concept=None,
        concepts=[Concept(name='', definition=None, uri=None)],
        aggregation_method=None,
        sources=[Source(id=None, name='', organization=None, type=None, note=None)],
        sources_note=None,
        data_collection=data_collection(data_source=None, method=None, period=None, note=None, uri=None),
        compliance=[ComplianceItem(standard='', abbreviation=None, custodian=None, uri=None)],
        framework=[
            FrameworkItem(
                name='',
                abbreviation=None,
                custodian=None,
                description=None,
                goal_id=None,
                goal_name=None,
                goal_description=None,
                target_id=None,
                target_name=None,
                target_description=None,
                indicator_id=None,
                indicator_name=None,
                indicator_description=None,
                uri=None,
                notes=None
            )
        ],
        limitation=None,
        quality_checks=None,
        quality_note=None,
        validation_rules=[],
        sources_discrepancies=None,
        adjustments=[],
        missing=None,
        errata=[ErrataItem(type=None, description=None)],
        time_periods=[Time_period(start=None, end=None)],
        ref_country=[Ref_countryItem(name=None, code=None)],
        geographic_units=[Geographic_unit(name='', code=None, type=None)],
        bbox=[BboxItem(west=None, east=None, south=None, north=None)],
        authoring_entity=[Authoring_entityItem(name='', affiliation=None, abbreviation='', email='', uri=None)],
        mandate=mandate(mandate=None, uri=None),
        measurement_unit=None,
        dimensions=[Dimension(name=None, label='', description=None)],
        release_calendar=None,
        periodicity=None,
        base_period=None,
        series_break=None,
        keywords=[Keyword(name='', vocabulary=None, uri=None)],
        topics=[Topic(id=None, name='', parent_id=None, vocabulary=None, uri=None)],
        themes=[Theme(id=None, name='', parent_id=None, vocabulary=None, uri=None)],
        disciplines=[Discipline(id=None, name='', parent_id=None, vocabulary=None, uri=None)],
        disaggregation=None,
        languages=[Language(name=None, code=None)],
        acronyms=[Acronym(acronym='', expansion='', occurence=None)],
        related_indicators=[Related_indicator(code=None, uri=None, label=None, relationship=None, type=None)],
        series_groups=[Series_group(name=None, description=None, version=None, uri=None)],
        notes=[Note(note=None, type=None)],
        license=[LicenseItem(name=None, uri=None, note=None)],
        confidentiality=None,
        confidentiality_status=None,
        confidentiality_note=None,
        links=[Link(type=None, description=None, uri=None)],
        api_documentation=[Api_documentationItem(description=None, uri=None)],
        contacts=[Contact(name=None, role=None, affiliation=None, email=None, telephone=None, uri=None)]
    ),
    tags=[Tag(tag=None, tag_group=None)]
)

We can also convert back to a dictionary and we can choose to simplfy which excludes Nones, empty strings, empty lists and empty dictionaries

In [15]:
me.change_mode_or_template(indicator_pydantic, output_mode='dict', simplify=True)

{'metadata_information': {'producers': [{'name': 'example_producer'}]}}

## Excel

Finally, a nicely formatted Excel file can be created into which the metadata can be written, with the name of the metadata type or of the default template used as the filename if no filename is explicitly given.

In [16]:
outline_filename = me.make_metadata_outline('indicator', 'excel')
outline_filename

'IHSN_INDICATOR_1-0_Template_v01_EN_metadata.xlsx'

In [17]:
indicator_excel = me.read_metadata_from_excel(outline_filename, 'indicator')

In [18]:
# Tidy up the file
os.remove(outline_filename)

## Retreiving existing metadata

Likewise, existing projects can be downloaded as either dictionaries, pydantic models or as excel spreadsheets.

In [19]:
demo_dict = me.get_project_metadata_by_id(indicator_id, output_mode='dict')
demo_dict

{'series_description': {'idno': 'GB20241030_demo', 'name': 'Version 1'}}

In [20]:
demo_pydantic = me.get_project_metadata_by_id(indicator_id, 'pydantic')
demo_pydantic

IHSN_INDICATOR_1-0_Template_v01_EN(metadata_information=metadata_information(title=None, idno=None, producers=[Producer(name=None, abbr=None, affiliation=None, role=None)], prod_date=None, version=None), series_description=series_description(idno='GB20241030_demo', alternate_identifiers=[Alternate_identifier(name=None, identifier='', database=None, uri=None, notes=None)], name='Version 1', aliases=[Aliase(alias=None)], database_id=None, definition_short=None, definition_long=None, definition_references=[Definition_reference(source=None, uri=None, note=None)], relevance=None, methodology=None, derivation=None, imputation=None, statistical_concept=None, concepts=[Concept(name='', definition=None, uri=None)], aggregation_method=None, sources=[Source(id=None, name='', organization=None, type=None, note=None)], sources_note=None, data_collection=data_collection(data_source=None, method=None, period=None, note=None, uri=None), compliance=[ComplianceItem(standard='', abbreviation=None, custodian=None, uri=None)], framework=[FrameworkItem(name='', abbreviation=None, custodian=None, description=None, goal_id=None, goal_name=None, goal_description=None, target_id=None, target_name=None, target_description=None, indicator_id=None, indicator_name=None, indicator_description=None, uri=None, notes=None)], limitation=None, quality_checks=None, quality_note=None, validation_rules=[], sources_discrepancies=None, adjustments=[], missing=None, errata=[ErrataItem(type=None, description=None)], time_periods=[Time_period(start=None, end=None)], ref_country=[Ref_countryItem(name=None, code=None)], geographic_units=[Geographic_unit(name='', code=None, type=None)], bbox=[BboxItem(west=None, east=None, south=None, north=None)], authoring_entity=[Authoring_entityItem(name='', affiliation=None, abbreviation='', email='', uri=None)], mandate=mandate(mandate=None, uri=None), measurement_unit=None, dimensions=[Dimension(name=None, label='', description=None)], release_calendar=None, periodicity=None, base_period=None, series_break=None, keywords=[Keyword(name='', vocabulary=None, uri=None)], topics=[Topic(id=None, name='', parent_id=None, vocabulary=None, uri=None)], themes=[Theme(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disciplines=[Discipline(id=None, name='', parent_id=None, vocabulary=None, uri=None)], disaggregation=None, languages=[Language(name=None, code=None)], acronyms=[Acronym(acronym='', expansion='', occurence=None)], related_indicators=[Related_indicator(code=None, uri=None, label=None, relationship=None, type=None)], series_groups=[Series_group(name=None, description=None, version=None, uri=None)], notes=[Note(note=None, type=None)], license=[LicenseItem(name=None, uri=None, note=None)], confidentiality=None, confidentiality_status=None, confidentiality_note=None, links=[Link(type=None, description=None, uri=None)], api_documentation=[Api_documentationItem(description=None, uri=None)], contacts=[Contact(name=None, role=None, affiliation=None, email=None, telephone=None, uri=None)]), tags=[Tag(tag=None, tag_group=None)])

In [21]:
excel_filename = demo_name+'.xlsx'
me.get_project_metadata_by_id(indicator_id, output_mode='excel', filename=excel_filename)

'GB20241030_demo.xlsx'

### Updating an existing project

You can create and update projects with metadata as either dictionaries, pydantic models or in Excel files.

In [22]:
me.update_project_log_by_id(indicator_id, demo_dict)

In [23]:
me.update_project_log_by_id(indicator_id, demo_pydantic)

In [24]:
me.update_project_log_by_id(indicator_id, excel_filename)

### Updating with patch updates

In [25]:
# tidy up the file called f"{demo_name}.xlsx"
os.remove(f"{demo_name}.xlsx")

# Collections

We can list and create collections, we can add and remove projects from collections and we can apply templates to collections.

In [26]:
me.list_collections().head()

,title,description,created,changed,created_by,changed_by,pid,wgt,username
id,,,,,,,,,
8,aL-moved,Collection description Text,1970-01-01T00:33:43+00:00,2024-02-06T04:04:35+00:00,13,20,None,None,chriskrestel
18,CCKP,World Bank Climate Change Knowledge Platform,2024-06-05T02:04:21+00:00,2024-06-05T02:04:21+00:00,2,2,None,None,Olivier Dupriez
85,Demo Collection,Demo Collection,2024-10-08T19:19:28+00:00,2024-10-08T19:19:28+00:00,25,25,None,None,vmascarinas
12,Emmanuel,None,2024-04-30T13:23:31+00:00,2024-04-30T13:23:31+00:00,2,2,None,None,Olivier Dupriez
20,geoflow,Projects published through geoflow (https://gi...,2024-06-11T19:35:48+00:00,2024-06-11T19:35:48+00:00,22,22,None,None,Emmanuel Blondel

In [27]:
collection_id = me.create_collection(demo_name+"_collection", description = "An example collection for demonstration")

In [28]:
me.get_collection_by_id(collection_id)

id                                                 156
title                       GB20241030_demo_collection
description    An example collection for demonstration
created                                     1732657104
changed                                     1732657104
created_by                                          24
changed_by                                          24
pid                                               None
wgt                                               None
dtype: object

### Populating collections

In [29]:
me.add_projects_to_collection(collection=collection_id, id_format='id', projects=[indicator_id])

In [30]:
me.list_projects_in_collection(collection=collection_id, limit=5)

,type,idno,study_idno,title,abbreviation,nation,year_start,year_end,published,created,changed,varcount,created_by,changed_by,is_shared,thumbnail,template_uid,username,username_cr,collections
id,,,,,,,,,,,,,,,,,,,,
3373,timeseries,e85bec4a-34fc-4a1b-af88-e93cb2750d36,GB20241030_demo,Version 1,None,,0,0,None,2024-11-26T21:38:18+00:00,2024-11-26T21:38:23+00:00,None,24,24,None,None,8603d94e27bccc2bdad1e00dbbf0fe32en,Gordon Blackadder,Gordon Blackadder,"[{'id': '156', 'title': 'GB20241030_demo_colle..."

In [31]:
me.remove_projects_from_collection(collection=collection_id, id_format='id', projects=[indicator_id])

### Deleting Collections

In [32]:
me.delete_collection_by_id(collection_id)

# Templates

Different organizations often want to specify the use of different subsets of metadata. We can list templates and see which templates are the default for our organization.

In [33]:
me.list_templates().head()

,uid,template_type,name,data_type,lang,template,default,id,version,organization,...,owner_id,deleted_at,deleted_by,is_deleted,owner_username,owner_email,changed_by_username,changed_by_email,created_by_username,created_by_email
0,microdata-system-en,core,Microdata DDI 2.5 EN,survey,en,metadata_editor/metadata_editor_templates/surv...,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,232ea3aaece0cdf1db157f797f6b92e5fr,core,IHSN DDI 2.5 Modèle v01 FR,survey,fr,metadata_editor/metadata_editor_templates/surv...,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6740f5f920502baf3f6cbcaa5c113deeen,core,IHSN DDI 2.5 Template v01 EN,survey,en,metadata_editor/metadata_editor_templates/surv...,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,timeseries-system-en,core,Indicator Schema 1.0 EN,timeseries,en,metadata_editor/metadata_editor_templates/time...,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8603d94e27bccc2bdad1e00dbbf0fe32en,core,IHSN INDICATOR 1.0 Template v01 EN,timeseries,en,metadata_editor/metadata_editor_templates/time...,True,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
me.get_template_by_uid("microdata-system-en")

uid                                            microdata-system-en
template_type                                                 core
name                                          Microdata DDI 2.5 EN
data_type                                                   survey
lang                                                            en
template         {'type': 'template', 'title': 'Microdata Proje...
Name: Microdata DDI 2.5 EN, dtype: object

### Template Classes

We can create a pydantic model for a given class

In [35]:
c = me.get_metadata_class("6740f5f920502baf3f6cbcaa5c113deeen")

In [36]:
c

template.IHSN_DDI_2-5_Template_v01_EN

In [37]:
c.model_fields

{'doc_desc': FieldInfo(annotation=Union[doc_desc, NoneType], required=False, default=None),
 'study_desc': FieldInfo(annotation=Union[study_desc, NoneType], required=False, default=None),
 'tags': FieldInfo(annotation=Union[List[Tag], NoneType], required=False, default=None, title='Tags', description='Tags, especially when organized in tag groups, provide a powerful and flexible solution to enable custom facets (filters) in data catalogs. Note that tags and tag groups are not element from the DDI Codebook standard.'),
 'additional': FieldInfo(annotation=additional, required=True, title='additional')}

But it's usually easier to start with an outline of the class. Again, this can be in either a dictionary, a pydantic model or as an Excel file.

In [38]:
me.make_metadata_outline("6740f5f920502baf3f6cbcaa5c113deeen", "pydantic").pretty_print()

IHSN_DDI_2-5_Template_v01_EN(
    doc_desc=doc_desc(
        producers=[Producer(name=None, abbr=None, affiliation=None, role=None)],
        prod_date=None,
        idno=None,
        version_statement=version_statement(
            version=None,
            version_date=None,
            version_resp=None,
            version_notes=None
        )
    ),
    study_desc=study_desc(
        title_statement=title_statement(
            title='',
            sub_title=None,
            alternate_title=None,
            translated_title=None,
            idno='',
            identifiers=[Identifier(type=None, identifier='')]
        ),
        series_statement=series_statement(series_name=None, series_info=None),
        version_statement=version_statement(
            version=None,
            version_date=None,
            version_resp=None,
            version_notes=None
        ),
        study_info=study_info(
            abstract=None,
            data_kind=None,
            analysis_unit=None,
            keywords=[Keyword(keyword=None, vocab=None, uri=None)],
            topics=[Topic(topic='', vocab=None, uri=None)],
            universe=None,
            nation=[NationItem(name='', abbreviation=None)],
            geog_coverage=None,
            geog_coverage_notes=None,
            geog_unit=None,
            bbox=[BboxItem(west=None, east=None, south=None, north=None)],
            bound_poly=[Bound_polyItem(lat=None, lon=None)],
            study_budget=None,
            coll_dates=[Coll_date(start='', end=None, cycle=None)],
            time_periods=[Time_period(start='', end=None, cycle=None)],
            quality_statement=quality_statement(
                compliance_description=None,
                standards=[Standard(name=None, producer=None)],
                other_quality_statement=None
            ),
            ex_post_evaluation=ex_post_evaluation(
                type=None,
                evaluation_process=None,
                evaluator=[EvaluatorItem(name='', abbr=None, affiliation=None, role=None)],
                completion_date=None,
                outcomes=None
            )
        ),
        authoring_entity=[Authoring_entityItem(name='', affiliation=None)],
        production_statement=production_statement(
            producers=[Producer(name=None, abbreviation=None, affiliation=None, role=None)],
            funding_agencies=[Funding_agencie(name='', abbr=None, grant=None, role=None)],
            copyright=None
        ),
        oth_id=[Oth_idItem(name='', affiliation=None, role=None)],
        study_authorization=study_authorization(
            date=None,
            agency=[AgencyItem(name='', affiliation=None, abbr=None)],
            authorization_statement=None
        ),
        method=method(
            data_collection=data_collection(
                sample_frame=sample_frame(
                    name=None,
                    valid_period=[Valid_periodItem(event=None, date='')],
                    custodian=None,
                    universe=None,
                    frame_unit=frame_unit(unit_type=None, is_primary=None, num_of_units=None),
                    update_procedure=None,
                    reference_period=[Reference_periodItem(event=None, date='')]
                ),
                sampling_procedure=None,
                sampling_deviation=None,
                weight=None,
                research_instrument=None,
                instru_development=None,
                time_method=None,
                frequency=None,
                sources=[Source(name=None, origin=None, characteristics=None)],
                coll_mode=[],
                data_collectors=[Data_collector(name=None, affiliation=None, abbr=None, role=None)],
                collector_training=[Collector_trainingItem(type=None, training=None)],
                control_operations=None,
                act_min=None,
                coll_situation=None,
                cleaning_operations=None,
                analysis_info=analysis_info(sampling_error_estimates=None, data_appraisal=None)
            ),
            analysis_info=analysis_info(response_rate=None),
            method_notes=None,
            data_processing=[Data_processingItem(type=None, description='')]
        ),
        study_development=study_development(
            development_activity=[
                Development_activityItem(
                    activity_type=None,
                    activity_description=None,
                    participants=[Participant(name='', affiliation=None, role=None)],
                    resources=[Resource(name=None, origin=None, characteristics=None)],
                    outcome=None
                )
            ]
        ),
        data_access=data_access(
            dataset_availability=dataset_availability(
                access_place=None,
                access_place_url=None,
                original_archive=None,
                coll_size=None,
                complete=None,
                file_quantity=None,
                notes=None,
                status=None
            ),
            dataset_use=dataset_use(
                contact=[ContactItem(name=None, affiliation=None, uri=None, email=None)],
                conf_dec=[Conf_decItem(required=None, txt=None, form_id=None, form_url=None)],
                conditions=None,
                cit_req=None,
                deposit_req=None,
                spec_perm=[Spec_permItem(required=None, txt=None, form_url=None, form_id=None)],
                restrictions=None,
                disclaimer=None
            ),
            notes=None
        ),
        distribution_statement=distribution_statement(
            depositor=[DepositorItem(name=None, abbr=None, affiliation=None, uri=None)],
            deposit_date=None,
            distributors=[Distributor(name='', abbr=None, affiliation=None, uri=None)],
            distribution_date=None,
            contact=[ContactItem(name=None, affiliation=None, email=None, uri=None)]
        ),
        study_notes=None
    ),
    tags=[Tag(tag=None, tag_group=None)],
    additional=additional(
        file_description=file_description(
            data_file=data_file(
                file_id='',
                file_name='',
                file_type=None,
                description=None,
                case_count=None,
                var_count=None,
                producer=None,
                data_checks=None,
                missing_data=None,
                version=None,
                notes=None
            )
        ),
        variable_description=variable_description(
            variable=variable(
                file_id='',
                vid='',
                name='',
                labl=None,
                var_universe=None,
                var_txt=None,
                var_concept=[Var_conceptItem(title=None, vocab=None, uri=None)],
                var_sumstat=[Var_sumstatItem(type=None, value=None, wgtd=None)],
                var_catgry=[
                    Var_catgryItem(value=None, label=None, stats=[Stat(type=None, value=None, wgtd=None)])
                ],
                var_std_catgry=[Var_std_catgryItem(name=None, source=None, date=None, uri=None)],
                var_intrvl=None,
                var_dcml=None,
                var_wgt=None,
                var_security=None,
                var_notes=None,
                var_respunit=None,
                var_qstn_preqtxt=None,
                var_qstn_qstnlit=None,
                var_qstn_postqtxt=None,
                var_forward=None,
                var_backward=None,
                var_qstn_ivuinstr=None,
                var_codinstr=None,
                var_imputation=None,
                var_derivation=None,
                var_format=var_format(type=None, name=None, note=None),
                loc_start_pos=None,
                loc_end_pos=None,
                loc_width=None,
                loc_rec_seg_no=None
            )
        ),
        variable_groups_container=variable_groups_container(
            variable_groups=variable_groups(
                vgid=None,
                variables=None,
                variable_groups=None,
                group_type=None,
                label=None,
                txt=None,
                definition=None,
                universe=None,
                notes=None
            )
        )
    )
)

In [39]:
me.make_metadata_outline("6740f5f920502baf3f6cbcaa5c113deeen", "dict")

{'doc_desc': {'producers': [{'name': None,
    'abbr': None,
    'affiliation': None,
    'role': None}],
  'prod_date': None,
  'idno': None,
  'version_statement': {'version': None,
   'version_date': None,
   'version_resp': None,
   'version_notes': None}},
 'study_desc': {'title_statement': {'title': '',
   'sub_title': None,
   'alternate_title': None,
   'translated_title': None,
   'idno': '',
   'identifiers': [{'type': None, 'identifier': ''}]},
  'series_statement': {'series_name': None, 'series_info': None},
  'version_statement': {'version': None,
   'version_date': None,
   'version_resp': None,
   'version_notes': None},
  'study_info': {'abstract': None,
   'data_kind': None,
   'analysis_unit': None,
   'keywords': [{'keyword': None, 'vocab': None, 'uri': None}],
   'topics': [{'topic': '', 'vocab': None, 'uri': None}],
   'universe': None,
   'nation': [{'name': '', 'abbreviation': None}],
   'geog_coverage': None,
   'geog_coverage_notes': None,
   'geog_unit': None,
   'bbox': [{'west': None, 'east': None, 'south': None, 'north': None}],
   'bound_poly': [{'lat': None, 'lon': None}],
   'study_budget': None,
   'coll_dates': [{'start': '', 'end': None, 'cycle': None}],
   'time_periods': [{'start': '', 'end': None, 'cycle': None}],
   'quality_statement': {'compliance_description': None,
    'standards': [{'name': None, 'producer': None}],
    'other_quality_statement': None},
   'ex_post_evaluation': {'type': None,
    'evaluation_process': None,
    'evaluator': [{'name': '',
      'abbr': None,
      'affiliation': None,
      'role': None}],
    'completion_date': None,
    'outcomes': None}},
  'authoring_entity': [{'name': '', 'affiliation': None}],
  'production_statement': {'producers': [{'name': None,
     'abbreviation': None,
     'affiliation': None,
     'role': None}],
   'funding_agencies': [{'name': '',
     'abbr': None,
     'grant': None,
     'role': None}],
   'copyright': None},
  'oth_id': [{'name': '', 'affiliation': None, 'role': None}],
  'study_authorization': {'date': None,
   'agency': [{'name': '', 'affiliation': None, 'abbr': None}],
   'authorization_statement': None},
  'method': {'data_collection': {'sample_frame': {'name': None,
     'valid_period': [{'event': None, 'date': ''}],
     'custodian': None,
     'universe': None,
     'frame_unit': {'unit_type': None,
      'is_primary': None,
      'num_of_units': None},
     'update_procedure': None,
     'reference_period': [{'event': None, 'date': ''}]},
    'sampling_procedure': None,
    'sampling_deviation': None,
    'weight': None,
    'research_instrument': None,
    'instru_development': None,
    'time_method': None,
    'frequency': None,
    'sources': [{'name': None, 'origin': None, 'characteristics': None}],
    'coll_mode': [],
    'data_collectors': [{'name': None,
      'affiliation': None,
      'abbr': None,
      'role': None}],
    'collector_training': [{'type': None, 'training': None}],
    'control_operations': None,
    'act_min': None,
    'coll_situation': None,
    'cleaning_operations': None,
    'analysis_info': {'sampling_error_estimates': None,
     'data_appraisal': None}},
   'analysis_info': {'response_rate': None},
   'method_notes': None,
   'data_processing': [{'type': None, 'description': ''}]},
  'study_development': {'development_activity': [{'activity_type': None,
     'activity_description': None,
     'participants': [{'name': '', 'affiliation': None, 'role': None}],
     'resources': [{'name': None, 'origin': None, 'characteristics': None}],
     'outcome': None}]},
  'data_access': {'dataset_availability': {'access_place': None,
    'access_place_url': None,
    'original_archive': None,
    'coll_size': None,
    'complete': None,
    'file_quantity': None,
    'notes': None,
    'status': None},
   'dataset_use': {'contact': [{'name': None,
      'affiliation': None,
      'uri': None,
      'email': None}],
    'conf_dec': [{'required': None,
      'txt': None,
      'form_id': None,
      'form_url': None}],
    'conditions': None,
    'cit_req': None,
    'deposit_req': None,
    'spec_perm': [{'required': None,
      'txt': None,
      'form_url': None,
      'form_id': None}],
    'restrictions': None,
    'disclaimer': None},
   'notes': None},
  'distribution_statement': {'depositor': [{'name': None,
     'abbr': None,
     'affiliation': None,
     'uri': None}],
   'deposit_date': None,
   'distributors': [{'name': '',
     'abbr': None,
     'affiliation': None,
     'uri': None}],
   'distribution_date': None,
   'contact': [{'name': None,
     'affiliation': None,
     'email': None,
     'uri': None}]},
  'study_notes': None},
 'tags': [{'tag': None, 'tag_group': None}],
 'additional': {'file_description': {'data_file': {'file_id': '',
    'file_name': '',
    'file_type': None,
    'description': None,
    'case_count': None,
    'var_count': None,
    'producer': None,
    'data_checks': None,
    'missing_data': None,
    'version': None,
    'notes': None}},
  'variable_description': {'variable': {'file_id': '',
    'vid': '',
    'name': '',
    'labl': None,
    'var_universe': None,
    'var_txt': None,
    'var_concept': [{'title': None, 'vocab': None, 'uri': None}],
    'var_sumstat': [{'type': None, 'value': None, 'wgtd': None}],
    'var_catgry': [{'value': None,
      'label': None,
      'stats': [{'type': None, 'value': None, 'wgtd': None}]}],
    'var_std_catgry': [{'name': None,
      'source': None,
      'date': None,
      'uri': None}],
    'var_intrvl': None,
    'var_dcml': None,
    'var_wgt': None,
    'var_security': None,
    'var_notes': None,
    'var_respunit': None,
    'var_qstn_preqtxt': None,
    'var_qstn_qstnlit': None,
    'var_qstn_postqtxt': None,
    'var_forward': None,
    'var_backward': None,
    'var_qstn_ivuinstr': None,
    'var_codinstr': None,
    'var_imputation': None,
    'var_derivation': None,
    'var_format': {'type': None, 'name': None, 'note': None},
    'loc_start_pos': None,
    'loc_end_pos': None,
    'loc_width': None,
    'loc_rec_seg_no': None}},
  'variable_groups_container': {'variable_groups': {'vgid': None,
    'variables': None,
    'variable_groups': None,
    'group_type': None,
    'label': None,
    'txt': None,
    'definition': None,
    'universe': None,
    'notes': None}}}}

## Deleting Projects

In [40]:
me.delete_project_by_id(indicator_id)

## Explanatory Error Messages

### When the URL is not secure

In [41]:
your_api_key = "bad key"
api_url = "http://example.org/index.php/api/"
me = MetadataEditor(api_url=api_url, api_key=your_api_key)

ValidationError: 1 validation error for RequestsWithSpecificErrors
  Value error, URL scheme should be 'https' but got http://example.org/index.php/api/To allow the less secure use of 'http', set allow_unsecure=True [type=value_error, input_value={'api_url': 'http://examp...lse, 'verify_ssl': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error

### When the api key is invalid

In [42]:
api_key = "bad_key"
me_bad = MetadataEditor(api_url="https://metadataeditorqa.worldbank.org/index.php/api",
                        api_key=api_key)
me_bad.list_projects(limit=5)

PermissionError: Access to that URL is denied. Check that the API key is correct

### When required data is missing or the type is incorred

In [43]:
series_description = {
                        "idno": 17,
                        "doi": "demoV1",
                     }

me.create_project_log('indicator', {"idno":"GB20240617_demo3", "series_description":series_description})

AttributeError: 'dict' object has no attribute 'lower'

### When the id is incorrect

In [44]:
series_description= {
                "idno": "GB20240617_demo1",
                "doi": "V2",
                "name": "Version 2",
                "display_name": "Version 2",
                "authoring_entity": [{"name": "example agency"}]
                }

me.update_project_log_by_id(1,
                           {"series_description":series_description})

PermissionError: {"status":"failed","message":"You don't have permissions to access this project"}